services:
  nest:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
